core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.homeView, name='home'),
    path('projects', views.ProjectsView.as_view(), name='projects'),
    path('projects/<slug:slug>', views.ProjectDetailView.as_view(),
         name='single_project'),
    path('thanks', views.ThanksView.as_view(), name='thanks'),
    path('contact', views.ContactFormView.as_view(), name='contact'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
import uuid
from ckeditor.fields import RichTextField
from django.db import models
from django.utils.text import slugify
from django.core.validators import MaxValueValidator, MinValueValidator


class Tag(models.Model):
    '''Tag model'''
    name = models.CharField(max_length=25)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        '''Return the name of the model'''
        return self.name


class ImageAlbum(models.Model):
    name = models.CharField(max_length=255, default='Album')

    def full(self):
        return self.images.all()

    def default(self):
        return self.images.filter(default=True).first()

    def thumbnails(self):
        return self.images.filter(width__lt=100, length_lt=100)

    def __str__(self):
        '''Return the name of the model'''
        return self.name


class Image(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/')
    default = models.BooleanField(default=False)
    width = models.FloatField(null=True, blank=True)
    height = models.FloatField(null=True, blank=True)
    album = models.ForeignKey(ImageAlbum, null=True, blank=True,
                              related_name='images',
                              on_delete=models.CASCADE)

    def __str__(self):
        '''Return the name of the model'''
        return self.name


class Project(models.Model):
    '''Model representing a project'''

    importance = models.PositiveIntegerField(default=5, validators=[
        MaxValueValidator(10),
        MinValueValidator(1)
    ])
    title = models.CharField(max_length=255)
    body = RichTextField(null=True, blank=True)
    thumbnail = models.ImageField(upload_to='thumbnails', blank=True)
    album = models.OneToOneField(ImageAlbum, null=True, blank=True,
                                 related_name='album',
                                 on_delete=models.CASCADE)
    slug = models.SlugField(null=True, blank=True)
    githuburl = models.URLField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    tag = models.ManyToManyField(Tag, blank=True)
    video = models.URLField(null=True, blank=True)
    gif = models.URLField(null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Project, self).save(*args, **kwargs)

    def __str__(self):
        '''Return the name of the model'''
        return self.title

core/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings


class ContactForm(forms.Form):
    topic = forms.CharField(max_length=255, required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

    def send_email(self):
        send_mail(
            self.cleaned_data['topic'],
            self.cleaned_data['message'],
            settings.EMAIL_HOST_USER,
            ['krzychu1232@gmail.com'],
            fail_silently=False
        )

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import FormView
from .forms import ContactForm
from .models import Project


def homeView(request):
    '''View for our home page'''
    return render(request, 'core/home.html')


class ProjectsView(ListView):
    '''View for projects model'''
    model = Project

    def get_queryset(self):
        return Project.objects.all().order_by('-importance')


class ProjectDetailView(DetailView):
    '''View for projects model'''
    model = Project


class ContactFormView(FormView):
    '''View for contact form'''
    template_name = 'core/contact.html'
    form_class = ContactForm
    success_url = 'thanks'

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class ThanksView(TemplateView):
    '''Thank you template'''
    template_name = 'core/thanks.html'

core/templates/core/contact.html
{% extends 'core/main.html' %}
{% load bootstrap5 %}
{% block content %}

<section class="contact">
    <div class="container">
        <form class="contact--form" method="POST">
            {% csrf_token %}
            {% bootstrap_form form%}
         <input type="submit" class="btn btn-default" value="Send">
        </form>
    </div>
</section>
{% endblock %}

core/templates/core/home.html
{% extends 'core/main.html' %}
{% load static %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container cnt-jumbo">
        <img class="mugshot display-4" src="{% static 'images/mugshot_2.png' %}">
        <div class="introduction-text lead">
            <h1>Krzysztof Kasprzyk</h1>
            <h3>Software developer, Industrial Robotics Engineer, Techie.</h3>
            <p>Contact me, and let’s make something awesome happen!</p>
        </div>
    </div>
</div>

{% endblock %}

core/templates/core/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>RSK_Code</title>
    <!--    Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <!--    Font Awesome-->
    <script src="https://kit.fontawesome.com/324afbc193.js" crossorigin="anonymous"></script>
    <!--    Medium Style Editor-->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css"
          type="text/css" media="screen" charset="utf-8">
    <!--    Custom CSS-->
    <link rel="stylesheet" href="{% static 'css/my_css.css' %}">
    <!--    Google FONTS-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>
{% include 'core/navbar.html' %}
{% block content %}
{% endblock %}
</body>
</html>

core/templates/core/navbar.html
{% load static %}
<nav class="navbar my_navbar navbar-expand-md navbar-dark navbar-static-top " role="navigation" id="navbar">

    <a class="navbar-brand" href="{% url 'core:home' %}"><img class="my_logo"
                                                              src="{% static 'images/logo_transparent.png' %}"></a>
    <div class="sm-links">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a href="https://www.linkedin.com/in/krzysztof-kasprzyk-a4180b187/">
                    <img class="icon" src="{% static 'icons/linkedin.png'%}"></a>
            </li>
            <li class="nav-item">
                <a href="https://github.com/rskrobotics?tab=repositories">
                    <img class="icon"
                         src="{% static 'icons/github_2.png'%}"></a>
            </li>
            <li class="nav-item">
                <a href="{% static 'images/Krzysztof_Kasprzyk_CV.pdf' %}">
                    <img class="icon" src="{% static 'icons/cv_2.png'%}"></a>
            </li>

        </ul>
    </div>
    <ul class="navbar-nav my_navbar_ul ml-auto">
        <li class="nav-item my_nav_item rounded"><a class="neon-button" href="{% url 'core:home' %}">Home</a></li>
        <li class="nav-item my_nav_item"><a class="neon-button" href="{% url 'core:projects' %}">
            Projects & work</a></li>
        <li class="nav-item my_nav_item"><a class="neon-button" href="{% url 'core:contact'%}">Contact me</a></li>
    </ul>
</nav>

core/templates/core/project_detail.html
{% extends 'core/main.html' %}
{% load static %}
{% block content %}
<div class="container detail_content">
    <h5>{{project.title}}</h5>
    <div class="row detail_body">
        {% for tag in project.tag.all %}
        <button class="col-lg-1 btn detail_tags tag">{{tag}}</button>
        {% endfor %}
    </div>
    <div class="row detail_content">
        {% for image in project.album.full %}
        <div class="col-vlg-4">
            <h5>{{image.name}}</h5>
            <a href="{{image.image.url}}"><img class="project_photo" src="{{image.image.url}}"></a>
        </div>
        {% endfor %}
    </div>
    {% if project.video %}
    <div class="text-center">
        <iframe width="907" height="510" src="{{project.video}}" title="YouTube video player"
                frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
    </div>
    {% endif %}
    {% if project.gif %}
    <img class="container gif" src="{{project.gif}}" border="0"/>
    {% endif %}
        {{project.body|safe}}
    <div class="row">
        {% if project.githuburl %}
        <a class="col-lg3 btn my_btn" href="{{project.githuburl}}">
            {% if project.title == "Robotics Engineering - all of automotive projects" %}
            Website
            {% else %}
            Code
            {% endif %}
        </a>
        {% endif %}
    </div>
</div>

{% endblock %}

core/templates/core/project_list.html
{% extends 'core/main.html' %}

{% block content %}
<section class="projects">
    <div class="container">
        {% if project_list %}
        <div class="row container">
            {% for project in project_list %}
            <div class="col-lg-4" >
                <div class="card my_card" style="width: 20rem;">
                    {% if project.thumbnail %}
                    <img class="project_thumbnail" src="{{project.thumbnail.url}}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{project.title}}</h5>
                        <div class="container">
                            <div class="row">
                                {% for tag in project.tag.all %}
                                <button class="btn tag">{{tag}}</button>
                                {% endfor %}
                            </div>
                            <div class="row">
                                <a class="btn my_btn col" href="{% url 'core:single_project' slug=project.slug %}">
                                    Details</a>
                                {% if project.githuburl %}
                                <a class="btn my_btn col" href="{{project.githuburl}}">
                                    {% if project.title == "Robotics Engineering - all of automotive projects" %}
                                    Website
                                    {% else %}
                                    Code
                                    {% endif %}
                                </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <h1>Sorry, no projects here. You are lazy.</h1>
        {% endif %}
    </div>
</section>

{% endblock %}

core/templates/core/skills.html
{% extends 'core/main.html' %}

{% block content %}

<h1>Skills</h1>

{% endblock %}

core/templates/core/thanks.html
{% extends 'core/main.html' %}
{% block content %}
<h3>Thank you, your message has been sent!</h3>
{% endblock %}